### PR TITLE
add help, list, unsubscribe commands

### LINKED ISSUE #11: Add support for `help`
Someone typing `/captain-hook help` should give them the syntax back

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #11, #16, #15 

screen shot 2016-05-26 at 4 48 16 pm

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
i'm not so happy with this code. r? @jefflembeck

**Comment by jefflembeck** [comment]
@ashleygwilliams what in particular do you not like about it? It seems pretty sensible.

**Comment by ashleygwilliams** [comment]
the /slack endpoint handlers are side-effecty and each call slack.chat individually when i think i'd rather have them return a message but the async shit got tricky and i decided to not mess around too much

**Comment by ashleygwilliams** [comment]
screen shot 2016-05-27 at 3 49 54 pm

**Comment by jefflembeck** [comment]
LGTM.

I think everything is nice and readable. We can refactor code later if necessary. Let's make it green now :)

**Comment by ashleygwilliams** [comment]
🐑 ↪️ ⚓

**Pull request merged**
